# Generated by Django 3.0.5 on 2020-05-29 11:50

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationDate', models.DateField(default=django.utils.timezone.now)),
                ('fullname', models.CharField(max_length=50)),
                ('registrationNo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator(), django.core.validators.EmailValidator])),
                ('mobileNumber', models.IntegerField()),
                ('idCard', models.FileField(upload_to='idUploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg'])])),
                ('numberOfTickets', models.IntegerField()),
                ('registrationType', models.CharField(choices=[('Self', 'Self'), ('Group', 'Group'), ('Corporate', 'Corporate'), ('Others', 'Others')], max_length=20)),
            ],
        ),
    ]
