# Generated by Django 3.0.5 on 2020-05-29 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='idCard',
            field=models.FileField(upload_to='media/idUploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg'])]),
        ),
    ]
