# Generated by Django 3.0.5 on 2020-05-29 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200529_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='idCard',
            field=models.FileField(upload_to='idUploads', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg'])]),
        ),
    ]
