# Generated by Django 3.0.5 on 2020-05-31 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200529_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='idCard',
            field=models.ImageField(upload_to='idUploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='registrationNo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
