# Generated by Django 3.0.5 on 2020-06-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20200601_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='numberOfTickets',
            field=models.IntegerField(default=1),
        ),
    ]
