# Generated by Django 3.0.5 on 2020-06-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20200604_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='numberOfTickets',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
