# Generated by Django 3.0.5 on 2020-06-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20200604_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='numberOfTickets',
            field=models.IntegerField(default=1),
        ),
    ]
